config/urls.py
# from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("files.urls", namespace="files")),
    path("users/", include("users.urls", namespace="users")),
    # path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # # Optional UI:
    # path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    # path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

files/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from files import views

app_name = "files"

urlpatterns = [
    path("", cache_page(60)(views.FilesListView.as_view()), name="files_list"),
    path(
        "folders/", cache_page(60)(views.FoldersListView.as_view()), name="folders_list"
    ),
    path("files/create/", views.FilesCreateView.as_view(), name="files_create"),
    path("files/delete/<int:pk>/", views.FilesDelete.as_view(), name="files_delete"),
    path(
        "folders/delete/<int:pk>/", views.FoldersDelete.as_view(), name="folders_delete"
    ),
    path(
        "folders/<int:pk>/",
        cache_page(60)(views.FilesByFoldersView.as_view()),
        name="files_by_folders",
    ),
    path("folders/create/", views.FoldersCreateView.as_view(), name="folders_create"),
    path(
        "files/",
        cache_page(60)(views.FavouritesFilesView.as_view()),
        name="files_by_favourites",
    ),
    path(
        "files/recent",
        cache_page(60)(views.RecentListView.as_view()),
        name="recent_files_and_folders",
    ),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import RegisterView, email_verification

app_name = "users"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
]

files/models.py
from django.db import models

from users.models import User


class Folders(models.Model):
    folders_name = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Владелец")

    def __str__(self):
        return f"{self.folders_name}"

    class Meta:
        verbose_name = "папка"
        verbose_name_plural = "папки"


class Files(models.Model):
    file_name = models.CharField(max_length=150)
    description = models.TextField(verbose_name="описание", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="дата создания")
    uploaded_file = models.FileField(
        upload_to="files/users_files", verbose_name="загрузка файла"
    )
    favorite = models.BooleanField(default=False)
    folder = models.ForeignKey(Folders, on_delete=models.CASCADE, blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Владелец")

    def __str__(self):
        return f"{self.file_name}"

    class Meta:
        verbose_name = "файл"
        verbose_name_plural = "файлы"

files/forms.py
from django import forms

from .models import Files, Folders


class FilesForm(forms.ModelForm):
    class Meta:
        model = Files
        fields = ["file_name", "uploaded_file", "folder", "favorite"]

    def __init__(self, *args, **kwargs):
        super(FilesForm, self).__init__(*args, **kwargs)

        self.fields["file_name"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите название товара"}
        )

        self.fields["uploaded_file"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите описание товара"}
        )

        self.fields["folder"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Загрузите изображение"}
        )

        self.fields["favorite"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Выберете категорию"}
        )


class FoldersForm(forms.ModelForm):
    class Meta:
        model = Folders
        fields = ["folders_name"]
        # widgets = {
        #     'file_name': forms.TextInput(attrs={
        #         'class': 'file_name_form',
        #         'placeholder': 'filename'
        #     }),
        #     'uploaded_file': forms.FileInput(attrs={
        #         'class': 'uploaded_file_form',
        #         # 'style': 'display: none;'
        #     })
        # }
        labels = {
            "folders_name": "",
        }
        help_texts = {
            "folders_name": "",
        }

        # labels = {'file_name':'',
        #           'uploaded_file': ''}

    def __init__(self, *args, **kwargs):
        super(FoldersForm, self).__init__(*args, **kwargs)

        self.fields["folders_name"].widget.attrs.update(
            {
                # 'class': 'file_name_form',
                "placeholder": "folders_name"
            }
        )

files/views.py
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DeleteView, ListView

from files.forms import FilesForm, FoldersForm
from files.models import Files, Folders
from files.services import (
    get_favourites_files,
    get_files_by_folders,
    recent_file_and_folders,
)


class FilesListView(LoginRequiredMixin,ListView):
    model = Files


class FilesCreateView(LoginRequiredMixin,CreateView):
    model = Files
    form_class = FilesForm
    success_url = reverse_lazy("files:files_list")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class FilesDelete(LoginRequiredMixin,DeleteView):
    model = Files
    success_url = reverse_lazy("files:files_list")
    permission_required = "files:delete_file"


class FoldersListView(LoginRequiredMixin,ListView):
    model = Folders


class FoldersCreateView(LoginRequiredMixin,CreateView):
    model = Folders
    form_class = FoldersForm
    success_url = reverse_lazy("files:folders_list")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class FoldersDelete(LoginRequiredMixin,DeleteView):
    model = Folders
    success_url = reverse_lazy("files:files_list")
    permission_required = "files:delete_folder"


class FilesByFoldersView(LoginRequiredMixin,ListView):
    model = Folders

    def get_queryset(self):
        folders_id = self.kwargs.get("pk")
        return get_files_by_folders(folders_id=folders_id)


class FavouritesFilesView(LoginRequiredMixin,ListView):
    model = Files

    def get_queryset(self):
        return get_favourites_files()


class RecentListView(LoginRequiredMixin,ListView):
    model = Folders, Files

    def get_queryset(self):
        return recent_file_and_folders()

files/templates/files/files_confirm_delete.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>

    <link rel="stylesheet" href="/static/css/files_list.css">
</head>

<body>


  <div class="body_cld">
    <div class="header_cloud">
      <div class="left_up_wnd">
        <h_cloud1>AAB_&laquo;Cloud&raquo;</h_cloud1>
      </div>
      <div class="mdl_up_wnd">
        <svg viewBox="0 0 132 87" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path id="Vector 1" d="M108.98 83C115.13 81.64 128 75.64 128 62.41C128 38.78 104.81 38.78 104.81 38.78C104.81 38.78 105.24 5.01 73.12 4C56.04 4 43.8 24.5 43.8 24.5C43.8 24.5 39.21 20.71 30.79 23.75C20.29 27.53 20.83 37.42 20.83 37.42C20.83 37.42 4 39.22 4 61.25C4 72.99 16.67 83 23.73 83L108.98 83Z" stroke="#FFFFFF" stroke-opacity="1" stroke-width="8" />
        </svg>
      </div>
      <div class="rgt_up_wnd">
        <div class="search-bar">
          <input type="text" placeholder="Search Files...">
        </div>
      </div>
    </div>
    <div class="left_container">
      <div class="menu">
         <div class="menu-btn-upload">
        <a href="{% url 'files:files_create' %}">Upload</a>
         </div>

          <div class="menu-btn-create">
        <a href="{% url 'files:folders_create' %}">Create</a>
         </div>


        <div class="menu-section">
          <span class="section-title">Category Files</span>
          <ul>
            <li><a href="{% url 'files:files_list' %}">All Files</a></li>
            <li><a href="{% url 'files:recent_files_and_folders' %}">Recent</a></li>
            <li><a href="{% url 'files:files_by_favourites' %}">Favourites</a></li>
          </ul>
        </div>

        <div class="menu-section">
          <span class="section-title">Folders</span>
          <ul>
            <li><a href="{% url 'files:folders_list' %}">All Folders</a></li>
          </ul>
        </div>

<!--        <div class="menu-section">-->
<!--          <span class="section-title">General Access</span>-->
<!--          <ul>-->
<!--            <li><a href="#">Files</a></li>-->
<!--            <li><a href="#">Folders</a></li>-->
<!--          </ul>-->
<!--        </div>-->
      </div>

    </div>
                      <div class="main_body">
                          <form class="row" method="post" enctype="multipart/form-data">

                          <h_cloud1 >ARE YOU SURE YOU WANT TO DELETE THE FILE-{{object.file_name}}?</h_cloud1>
                          {% csrf_token %}
                          <div class="upload_file">

                                <button type="submit" class="btn btn-danger ">Удалить</button>

                                <a href="{% url 'files:files_list' %}">CANCEL</a>
                  </div>
                               </form>
                  </div>

	</div>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

files/templates/files/files_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
   <link rel="stylesheet" href="/static/css/test.css">
    <title>Title</title>
</head>
<body>
<div class="body_cld">
    <div class="header_cloud">
      <div class="left_up_wnd">
        <h_cloud1>AAB_&laquo;Cloud&raquo;</h_cloud1>
      </div>
      <div class="mdl_up_wnd">
        <svg viewBox="0 0 132 87" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path id="Vector 1" d="M108.98 83C115.13 81.64 128 75.64 128 62.41C128 38.78 104.81 38.78 104.81 38.78C104.81 38.78 105.24 5.01 73.12 4C56.04 4 43.8 24.5 43.8 24.5C43.8 24.5 39.21 20.71 30.79 23.75C20.29 27.53 20.83 37.42 20.83 37.42C20.83 37.42 4 39.22 4 61.25C4 72.99 16.67 83 23.73 83L108.98 83Z" stroke="#FFFFFF" stroke-opacity="1" stroke-width="8" />
        </svg>
      </div>
      <div class="rgt_up_wnd">
        <div class="search-bar">
          <input type="text" placeholder="Search Files...">
        </div>
      </div>
    </div>
    <div class="left_container">
      <div class="menu">
        <div class="menu-btn-upload">
        <a href="{% url 'files:files_create' %}">Upload</a>
         </div>

          <div class="menu-btn-create">
        <a href="{% url 'files:folders_create' %}">Create</a>
         </div>

        <div class="menu-section">
          <span class="section-title">Category Files</span>
          <ul>
            <li><a href="{% url 'files:files_list' %}">All Files</a></li>
            <li><a href="#">Recent</a></li>
            <li><a href="{% url 'files:files_by_favourites' %}">Favourites</a></li>
          </ul>
        </div>

        <div class="menu-section">
          <span class="section-title">Folders</span>
          <ul>
            <li><a href="{% url 'files:folders_list' %}">All Folders</a></li>
          </ul>
        </div>
      </div>

    </div>
                      <div class="main_body">
                          <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                              <div class="start-btn">
                            <button type="submit" class="start-btn">Upload</button>
                                  </div>
                          </form>
                      </div>

	</div>
</body>
</html>

files/templates/files/files_list.html
<!DOCTYPE html>
<html lang="en">
{% if user.is_authenticated %}
<head>
    <meta charset="UTF-8">
   <link rel="stylesheet" href="/static/css/files_list_copy.css">
    <title>Title</title>
</head>
<body>
  <div class="body_cld">
    <div class="header_cloud">
      <div class="left_up_wnd">
        <h_cloud1>AAB_&laquo;Cloud&raquo;</h_cloud1>
      </div>
      <div class="mdl_up_wnd">
        <svg viewBox="0 0 132 87" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path id="Vector 1" d="M108.98 83C115.13 81.64 128 75.64 128 62.41C128 38.78 104.81 38.78 104.81 38.78C104.81 38.78 105.24 5.01 73.12 4C56.04 4 43.8 24.5 43.8 24.5C43.8 24.5 39.21 20.71 30.79 23.75C20.29 27.53 20.83 37.42 20.83 37.42C20.83 37.42 4 39.22 4 61.25C4 72.99 16.67 83 23.73 83L108.98 83Z" stroke="#FFFFFF" stroke-opacity="1" stroke-width="8" />
        </svg>
      </div>
      <div class="rgt_up_wnd">
        <div class="search-bar">
          <input type="text" placeholder="Search Files...">
        </div>
      </div>
    </div>
    <div class="left_container">
      <div class="menu">
         <div class="menu-btn-upload">
        <a href="{% url 'files:files_create' %}">Upload</a>
         </div>

          <div class="menu-btn-create">
        <a href="{% url 'files:folders_create' %}">Create</a>
         </div>


        <div class="menu-section">
          <span class="section-title">Category Files</span>
          <ul>
            <li><a href="{% url 'files:files_list' %}">All Files</a></li>
            <li><a href="{% url 'files:recent_files_and_folders' %}">Recent</a></li>
            <li><a href="{% url 'files:files_by_favourites' %}">Favourites</a></li>
          </ul>
        </div>

        <div class="menu-section">
          <span class="section-title">Folders</span>
          <ul>
            <li><a href="{% url 'files:folders_list' %}">All Folders</a></li>
          </ul>
        </div>

<!--        <div class="menu-section">-->
<!--          <span class="section-title">General Access</span>-->
<!--          <ul>-->
<!--            <li><a href="#">Files</a></li>-->
<!--            <li><a href="#">Folders</a></li>-->
<!--          </ul>-->
<!--        </div>-->
      </div>

    </div>
                      <div class="main_body">

                      {% for files in object_list %}
                          {% if files.owner == request.user or user.is_superuser %}
                            <div class="upload_file">

                                <a class="file_name">  {{files.file_name}}</a>

                                <a class="Download" href="{{files.uploaded_file.url}}">Download</a>

                                <a class="date_time">{{files.created_at}}</a>
                                {% if files.favorite == True %}
                                <a href="{% url 'files:files_by_favourites' %}">Favorite</a>
                                {% endif %}
                                <a  class="file_name" href="{% url 'files:files_delete' files.pk %}">Delete</a>
                  </div>
                   {% endif %}
                  {% endfor %}
	</div>
     </div>

{% else %}
<head>
    <meta charset="UTF-8">
   <link rel="stylesheet" href="/static/css/start_page.css">
    <title>Title</title>
</head>
<body>
    <div class="Telo">
        <div class="window">
        <h1>AAB_&laquo;project&raquo;
        </h1>
        <div class="text">
            <h2>This is a universe where technology, innovation and impeccable design merge into a powerful symbiosis, creating a </h2>
            <h2>platform that redefines the very notion of functionality. From advanced analytics and automation to interactive</h2>
            <h2> services that adapt to your needs, it's not just tools, but an ecosystem of solutions. Every detail has been thought out</h2>
            <h2>so you can feel the future today. This is not a website - it's a digital organism, where our ideas meet human creativity</h2>
            <h2>and complex algorithms work for the simplicity of your experience.</h2>
        </div>
            <div class="start-btn">
        <a href="{% url 'users:login' %}">GET STARTED</a>
                </div>
    </div>
        </div>

    <div class="author">
        <div class="footer-container">
            <div class="footer-text">Designed by: Sib_Semeonoff / Dew: Ilyacgproject</div>
            <div class="line_1"></div>
            <div class="footer-text">All rights reserved</div>
        </div>
    </div>
</body>
{% endif %}
</html>

files/templates/files/folders_confirm_delete.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>

    <link rel="stylesheet" href="/static/css/files_list.css">
</head>

<body>


  <div class="body_cld">
    <div class="header_cloud">
      <div class="left_up_wnd">
        <h_cloud1>AAB_&laquo;Cloud&raquo;</h_cloud1>
      </div>
      <div class="mdl_up_wnd">
        <svg viewBox="0 0 132 87" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path id="Vector 1" d="M108.98 83C115.13 81.64 128 75.64 128 62.41C128 38.78 104.81 38.78 104.81 38.78C104.81 38.78 105.24 5.01 73.12 4C56.04 4 43.8 24.5 43.8 24.5C43.8 24.5 39.21 20.71 30.79 23.75C20.29 27.53 20.83 37.42 20.83 37.42C20.83 37.42 4 39.22 4 61.25C4 72.99 16.67 83 23.73 83L108.98 83Z" stroke="#FFFFFF" stroke-opacity="1" stroke-width="8" />
        </svg>
      </div>
      <div class="rgt_up_wnd">
        <div class="search-bar">
          <input type="text" placeholder="Search Files...">
        </div>
      </div>
    </div>
    <div class="left_container">
      <div class="menu">
         <div class="menu-btn-upload">
        <a href="{% url 'files:files_create' %}">Upload</a>
         </div>

          <div class="menu-btn-create">
        <a href="{% url 'files:folders_create' %}">Create</a>
         </div>


        <div class="menu-section">
          <span class="section-title">Category Files</span>
          <ul>
            <li><a href="{% url 'files:files_list' %}">All Files</a></li>
            <li><a href="{% url 'files:recent_files_and_folders' %}">Recent</a></li>
            <li><a href="{% url 'files:files_by_favourites' %}">Favourites</a></li>
          </ul>
        </div>

        <div class="menu-section">
          <span class="section-title">Folders</span>
          <ul>
            <li><a href="{% url 'files:folders_list' %}">All Folders</a></li>
          </ul>
        </div>

<!--        <div class="menu-section">-->
<!--          <span class="section-title">General Access</span>-->
<!--          <ul>-->
<!--            <li><a href="#">Files</a></li>-->
<!--            <li><a href="#">Folders</a></li>-->
<!--          </ul>-->
<!--        </div>-->
      </div>

    </div>
                      <div class="main_body">
                          <form class="row" method="post" enctype="multipart/form-data">

                          <h_cloud1 >ARE YOU SURE YOU WANT TO DELETE THE FOLDER-{{object.folder_name}}?</h_cloud1>
                          {% csrf_token %}
                          <div class="upload_file">

                                <button type="submit" class="btn btn-danger ">Удалить</button>

                                <a href="{% url 'files:files_list' %}">CANCEL</a>
                  </div>
                               </form>
                  </div>

	</div>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

files/templates/files/folders_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
   <link rel="stylesheet" href="/static/css/test.css">
    <title>Title</title>
</head>
<body>
<div class="body_cld">
    <div class="header_cloud">
      <div class="left_up_wnd">
        <h_cloud1>AAB_&laquo;Cloud&raquo;</h_cloud1>
      </div>
      <div class="mdl_up_wnd">
        <svg viewBox="0 0 132 87" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path id="Vector 1" d="M108.98 83C115.13 81.64 128 75.64 128 62.41C128 38.78 104.81 38.78 104.81 38.78C104.81 38.78 105.24 5.01 73.12 4C56.04 4 43.8 24.5 43.8 24.5C43.8 24.5 39.21 20.71 30.79 23.75C20.29 27.53 20.83 37.42 20.83 37.42C20.83 37.42 4 39.22 4 61.25C4 72.99 16.67 83 23.73 83L108.98 83Z" stroke="#FFFFFF" stroke-opacity="1" stroke-width="8" />
        </svg>
      </div>
      <div class="rgt_up_wnd">
        <div class="search-bar">
          <input type="text" placeholder="Search Files...">
        </div>
      </div>
    </div>
    <div class="left_container">
      <div class="menu">
        <div class="menu-btn-upload">
        <a href="{% url 'files:files_create' %}">Upload</a>
         </div>

          <div class="menu-btn-create">
        <a href="{% url 'files:folders_create' %}">Create</a>
         </div>

        <div class="menu-section">
          <span class="section-title">Category Files</span>
          <ul>
            <li><a href="{% url 'files:files_list' %}">All Files</a></li>
            <li><a href="#">Recent</a></li>
            <li><a href="{% url 'files:files_by_favourites' %}">Favourites</a></li>
          </ul>
        </div>

        <div class="menu-section">
          <span class="section-title">Folders</span>
          <ul>
            <li><a href="{% url 'files:folders_list' %}">All Folders</a></li>
          </ul>
        </div>
      </div>

    </div>
                      <div class="main_body">
                          <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                              <div class="start-btn">
                            <button type="submit" class="start-btn">Upload</button>
                                  </div>
                          </form>
                      </div>

	</div>
</body>
</html>

files/templates/files/folders_list.html
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/css/folders_list.css">
    <title>Title</title>
</head>
<div class="body_cld">
    <div class="header_cloud">
        <div class="left_up_wnd">
            <h_cloud1>AAB_&laquo;Cloud&raquo;</h_cloud1>
        </div>
        <div class="mdl_up_wnd">
            <svg viewBox="0 0 132 87" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path id="Vector 1" d="M108.98 83C115.13 81.64 128 75.64 128 62.41C128 38.78 104.81 38.78 104.81 38.78C104.81 38.78 105.24 5.01 73.12 4C56.04 4 43.8 24.5 43.8 24.5C43.8 24.5 39.21 20.71 30.79 23.75C20.29 27.53 20.83 37.42 20.83 37.42C20.83 37.42 4 39.22 4 61.25C4 72.99 16.67 83 23.73 83L108.98 83Z" stroke="#FFFFFF" stroke-opacity="1" stroke-width="8" />
            </svg>
        </div>
        <div class="rgt_up_wnd">
            <div class="search-bar">
                <input type="text" placeholder="Search Files...">
            </div>
        </div>
    </div>
    <div class="left_container">
        <div class="menu">
            <div class="menu-btn-upload">
                <a href="{% url 'files:files_create' %}">Upload</a>
            </div>

            <div class="menu-btn-create">
                <a href="{% url 'files:folders_create' %}">Create</a>
            </div>

            <div class="menu-section">
                <span class="section-title">Category Files</span>
                <ul>
                    <li><a href="{% url 'files:files_list' %}">All Files</a></li>
                    <li><a href="{% url 'files:recent_files_and_folders' %}">Recent</a></li>
                    <li><a href="{% url 'files:files_by_favourites' %}">Favourites</a></li>
                </ul>
            </div>

            <div class="menu-section">
                <span class="section-title">Folders</span>
                <ul>
                    <li><a href="#">All Folders</a></li>
                </ul>
            </div>

            <!--        <div class="menu-section">-->
            <!--          <span class="section-title">General Access</span>-->
            <!--          <ul>-->
            <!--            <li><a href="#">Files</a></li>-->
            <!--            <li><a href="#">Folders</a></li>-->
            <!--          </ul>-->
            <!--        </div>-->
            <!--      </div>-->

        </div>
        <div class="main_body">
            {% for folders in object_list %}
            {% if folders.owner == request.user or user.is_superuser  %}
            <div class="upload_file">
                <a href="{% url 'files:files_by_folders' folders.id %}" >{{folders.folders_name}}</a>
                <a href="{% url 'files:folders_delete' folders.pk %}" >DELETE</a>
                <!--            <a href="{{folders.folders_name.url}}" >{{folders.folders_name}}</a>-->
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>

files/templates/files/header.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="#}">Контакты</a>


    </nav>
</div>